### ISSUE TITLE
Bad interaction with external transition-group

### ISSUE THREAD

**Issue by DarthGandalf** [Jexordexan/vue-slicksort#57]
I'm trying to remove elements from the list via special buttons, with animations.
I can make either sorting work, or delete animation, but not both.

```vue
<SortableList lockAxis="y" :useDragHandle="true" v-model="items">
  <transition-group name="list">
    <SortableListItem v-for="(item, index) in items" :index="index" :key="item.key"
        class="md-elevation-1 list-item">
      <md-icon v-handle>reorder</md-icon>
      <md-field class="md-layout-item">
        <md-input v-model="item.name"></md-input>
      </md-field>
      <md-button class="md-icon-button" @click="deleteItem(index)">
        <md-icon>delete</md-icon>
      </md-button>
    </SortableListItem>
  </transition-group>
</SortableList>
```
```css
.list-item {
  transition: all 1s;
}
.list-enter-active, .list-leave-active {
  position: absolute;
}
.list-enter, .list-leave-to {
  opacity: 0;
  transform: translateX(300px);
}
```
```js
data: () => ({
  items: [{name:'foo', key: 0}, {name:'bar', key: 1}, {name:'baz', key:2}],
}),
methods: {
  deleteItem(index) {
    this.items.splice(index, 1);
  }
},
```
This shows correct animation for deleting, but when I'm trying to drag one of items, they start jumping around. Removing `transition-group` fixes it.
I suspect this has something to do with `:key`, but when I'm changing to `:key="index"`, it also starts lagging, and it still doesn't work.
